### ISSUE TITLE
java.lang.NoSuchFieldError: no "J" field "value" in class "Ljava/lang/Long;" or its superclasses

### ISSUE THREAD

**Issue by ericliang** [maxim-top/maxim-android#2]
客户报错：
```
java.lang.NoSuchFieldError: no "J" field "value" in class "Ljava/lang/Long;" or its superclasses
        at im.floo.floolib.flooJNI.BMXClient_signUpNewUser(Native Method)
        at im.floo.floolib.BMXClient.signUpNewUser(BMXClient.java:160)
        at im.floo.floolib.BMXUserManager$1.exec(BMXUserManager.java:29)
        at im.floo.AsyncExecutor$1.run(AsyncExecutor.java:16)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

版本：0428lib
机型：pixel 2 Android 9

**Comment by ericliang** [comment]
Log：
```
W/floo_log: <2020/06/08 15:15:08:014> <W> signUpNewUser() retCode : 0
2020-06-08 15:15:08.014 26810-27005/com.example.myapplication D/floo_log: <2020/06/08 15:15:08:014> <D> signUpNewUser() response : {"code":200,"data":{"user_id":6601712323904,"auto_download":false,"group_confirm":false,"no_sounds":false,"no_push":false,"vibratory":false,"no_push_detail":false,"auth_mode":0,"no_push_start_hour":0,"no_push_end_hour":0}}
```

**Comment by ericliang** [comment]
使用 Demo APK 也能发现错误，但被屏蔽：

```
554 3047-3370/top.maxim.im W/floo_log: <2020/06/08 17:49:23:554> <W> signUpNewUser() retCode : 0
2020-06-08 17:49:23.554 3047-3370/top.maxim.im D/floo_log: <2020/06/08 17:49:23:554> <D> signUpNewUser() response : {"code":200,"data":{"user_id":6601714748672,"auto_download":false,"group_confirm":false,"no_sounds":false,"no_push":false,"vibratory":false,"no_push_detail":false,"auth_mode":0,"no_push_start_hour":0,"no_push_end_hour":0}}
2020-06-08 17:49:23.555 3047-3370/top.maxim.im W/top.maxim.im: Accessing hidden field Ljava/lang/Long;->value:J (greylist-max-p, JNI, allowed)
```

**Comment by h001erolee** [comment]
已解决。用Long型数组来返回值，而不是修改Long的属性。
